services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    image: orizen-flow-api:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - INTERNAL_API_URL=http://api:4000
      - REDIS_URL=redis://redis:6379
    ports:
      - "4000:4000"
    depends_on:
      - redis

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    image: orizen-flow-web:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - INTERNAL_API_URL=http://api:4000
    ports:
      - "3000:3000"
    depends_on:
      - api

  worker-fetch:
    build:
      context: .
      dockerfile: apps/worker/Dockerfile
    image: orizen-flow-worker:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379
      - INTERNAL_API_URL=http://api:4000
      - WORKER_TYPE=fetch
      - WORKER_CONCURRENCY=20
      - ENABLE_PLAYWRIGHT=false
      - MAX_BROWSER_PAGES=4
      - PLAYWRIGHT_VISIBLE_TEXT_THRESHOLD=999999
    cpus: 2
    mem_limit: 4g
    depends_on:
      - redis

  worker-browser:
    build:
      context: .
      dockerfile: apps/worker/Dockerfile
    image: orizen-flow-worker:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379
      - INTERNAL_API_URL=http://api:4000
      - WORKER_TYPE=browser
      - WORKER_CONCURRENCY=4
      - MAX_BROWSER_PAGES=4
      - PLAYWRIGHT_VISIBLE_TEXT_THRESHOLD=300
    cpus: 3
    mem_limit: 10g
    depends_on:
      - redis
