FROM oven/bun:latest AS base

FROM base AS prepare
WORKDIR /app
RUN bun install --global turbo
COPY . .
RUN turbo prune @api/hono --docker

FROM base AS builder
WORKDIR /app
COPY --from=prepare /app/.env .
COPY --from=prepare /app/.github/ ./.github/
COPY --from=prepare /app/out/json/ .
COPY --from=prepare /app/out/bun.lock .
RUN bun install --frozen-lockfile --ignore-scripts
COPY --from=prepare /app/out/full/ .
ENV NODE_ENV=production
RUN bun run build

FROM base AS runner
WORKDIR /app
COPY --from=builder --chown=bun:bun /app/node_modules/ ./node_modules/
COPY --from=builder --chown=bun:bun /app/apps/api/ ./apps/api/
COPY --from=builder --chown=bun:bun /app/packages/ ./packages/

USER bun
WORKDIR /app/apps/api
CMD ["bun", "run", "start"]
EXPOSE 4000
